# Generated by Django 5.1.6 on 2025-02-20 09:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(help_text="Электронная почта", max_length=254, verbose_name="Email")),
                ("country", models.CharField(help_text="Страна", max_length=150, verbose_name="Country")),
                ("city", models.CharField(help_text="Город", max_length=150, verbose_name="City")),
                ("street", models.CharField(help_text="Улица", max_length=150, verbose_name="Street")),
                ("house_number", models.CharField(help_text="Номер дома", max_length=10, verbose_name="House number")),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "ordering": ("country", "city", "street", "house_number"),
            },
        ),
        migrations.CreateModel(
            name="NetworkElement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Название", max_length=150, verbose_name="Name")),
                (
                    "debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Задолженность перед поставщиком",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Debt",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Дата и время создания", verbose_name="Date of creation"
                    ),
                ),
                (
                    "contact_data",
                    models.OneToOneField(
                        help_text="Контактные данные",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="element",
                        to="network.contactdata",
                        verbose_name="Contact data",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Поставщик",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customers",
                        to="network.networkelement",
                        verbose_name="Supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Network element",
                "verbose_name_plural": "Network elements",
                "ordering": ("created_at",),
            },
        ),
    ]
