# Generated by Django 5.1.6 on 2025-02-20 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Название товара.", max_length=150, verbose_name="Name")),
                (
                    "model",
                    models.CharField(
                        help_text="Модель или артикул товара.", max_length=200, unique=True, verbose_name="Model"
                    ),
                ),
                (
                    "release_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Дата выхода продукта на рынок.", verbose_name="Release date"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        help_text="Поставщик товара.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="network.networkelement",
                        verbose_name="Supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ("release_date",),
            },
        ),
    ]
